### PR TITLE
GUI: custom ipfs viewer url

### LINKED ISSUE #897: Add ability to use custom base URL for IPFS viewing
When [PR # 30](https://github.com/RavenProject/Ravencoin/pull/820) was adopted, it helpfully added the ability to view IPFS hashes from the QT through the Cloudflare gateway.  

At the time the code for this PR was written, it was suggested to allow QT wallet users to specify their own base URL (rather than requiring use of Cloudflare).  The author of the PR [indicated](https://github.com/RavenProject/Ravencoin/pull/820#issuecomment-694342147) that using Cloudflare was the first step, but that a configuration option would be added at a later time.  This remains a good idea.

As pointed out to me by @jeroz1, the QT wallet interface currently allows the user to specify their own base URL for viewing transaction information on third-party explorers:
image

Similar functionality could be added, in the same spot, to permit users to specify the base URL for IPFS hash viewing, changing the Cloudflare default used in PR 30.

This would facilitate users' ability to view more complex data structures than Cloudflare's gateway will allow:

Coudflare:

image

Custom viewer:
image

Note:  This suggestion is in addition to, not in lieu of, [Proposed Simple Standard For Asset Metadata Viewing In RVN QT #877](https://github.com/RavenProject/Ravencoin/issues/877), which proposes one workable method to allow asset issuers to specify an asset viewer when creating an asset, so that it can be viewed as intended by the asset issuer with customized third-party viewers.

### PR DESCRIPTION
**Pull request by fdoving**
Add the ability to set ipfs-url in options.  Closes #897
Defaults to https://ipfs.io/ipfs/

Naming of the labels, tooltips and such probably need some work.

### CODE REVIEW

**Comment by jeroz1** [comment]
Thanks for this. Doug and I were actually talking about this as it is related to #851. I have not built your solution yet but was wondering if your solution is placed next to third party explorer URL and handled the same way. And if so, if you would be willing to implement the changes that I suggested here: https://github.com/RavenProject/Ravencoin/pull/851#issuecomment-800890669

**Comment by jeroz1** [comment]
Added screen shot for convenience.

I have mixed feelings about setting a default. But also not sure if users would know what to fill out. Either way. I think the ipfs link and block explorer link behavior should be exactly the same.

**Comment by jeroz1** [comment]
# Overview of default settings screen
settings1
**Feedback**
- Change IPFS Viewer URL tool tip from `... %s in the URL is replaced with the hash` to `... %s in the URL is replaced by IPFS hash`
- Add reset buttons for tx and IPFS URLs. So users do not have to wipe ALL settings to change things back.
- Add `https://explorer.mangofarmassets.com/tx/%s` and `https://blockbook.ravencoin.org/tx/%s` to default explorer list

# Blank settings
settings2
**Feedback**
- Change `https://ipfs.io/ipfs/%s` to `https://example.com/ipfs/%s`

# Right click tx menu
settings3
**Feedback**
- Add option *Transaction URL settings...* above the third party transaction URLs and link it to Wallet > Options > Display (and, if possible, put the cursor in the Third party transaction URLs line).

**Comment by fdoving** [comment]
I'll look into this.

The default browsers is its own thing.
We should have a separate PR for that.

**Review by HyperPeek — APPROVED** [review]

**Pull request closed without merging**
