### PR TITLE
gui: create and reissue asset views - browse ipfs button

### PR DESCRIPTION
**Pull request by fdoving**
* Add button to open ipfs-hash in the configured ipfs-viewer.
      This can be handy to verify your ipfs-hash is correct, before creating the asset.

    * Remove a check that enabled the Check Availability button once the `Add IPFS/Txid hash` was enabled.

### CODE REVIEW

**Comment by fdoving** [comment]
image
image

**Comment by fdoving** [comment]
Manage Assets view: 
image
image

**Review by HyperPeek — APPROVED** [review]
approved fdcaddcd4027808773822394a9b827f3556d7b31 c745047f74858db572680cedd2df5c18c83f8228

**Review by hans-schmidt — APPROVED** [review]
Approved

**Pull request merged**
