### PR TITLE
ISE-RAVEN-2020-02

### PR DESCRIPTION
**Pull request by HenryGSI**

### CODE REVIEW

**Comment by jeroz1** [comment]
I do not understand this. The flag cannot be 0 and 1 at the same time. Wouldn't this skip the entire if-statement in all cases?

**Comment by HenryGSI** [comment]
According to the Audit, in the Faulty ISE-RAVEN-2020-02:

https://raven.foundation/CodeSecurityAudit/ise-ravencoin-assessment-202012-r1.pdf

On line 4520 of ‘src/assets/assets.cpp#L45201 ’ there is a check to ensure that the value of the ‘flag’ variable must be either 0 or 1. However, this expression is faulty and will always evaluate to true, indicating that the ‘flag’ value is not 0 or 1 even in cases where it is. The affected code is shown below:
```
 if (flag != 0 || flag != 1) {
 strError = _("Flag must be 1 or 0");
 return false;
 }
```
This fault is likely due to the use of the || operator and not the intended && operator. Correct usage of this expression is present on ‘src/assets/assets.cpp#L49392’ and shown below:
```
 if (flag != 0 && flag != 1) {
 strError = "bad-txns-null-data-flag-must-be-0-or-1";
 return false;
```
The flag always has to be 1 or 0, right?

If in any case it were different from 1 or 0, what would happen?

If you think the code is fine and would not give any error, leave it as it is now and can you close it.

Regards

**Comment by jeroz1** [comment]
Thanks for the explanation. Perhaps it's my lack of C knowledge of to understand what && does :).

**Comment by spyder46n2** [comment]
The strangeness of this error is why we (Tron or myself) haven't pushed this change in and created a release. I have been working with this change on and off for over a week making sure that there are no negative repercussions in changing this. Based on my testing it doesn't look like this will really make any difference. The logic is wrong and should be corrected, but we were making sure that logic even needed to exist. I'm working on a test that attempts to validate this change, until I had something working for that I wasn't in a hurry to commit any changes. I do think that resolving this needs to happen so this PR is perfectly valid. Feel free to create a build and pound on it using testnet/regtest (if you need some testnet RVN just send me an address and I can supply). I'll share my tests and create a PR with what I already have so others can validate my findings.

**Comment by HenryGSI** [comment]
Perhaps the function '[CNullAssetTxData::IsValid()](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/assets.cpp#L4507)' where is this 'IF' isn't used and therefore does not send any errors.


The other function ['VerifyNullAssetDataFlag()'](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/assets.cpp#L4936) where is the other 'IF', is used more times.


It may be outdated code from older versions.

But if someone ever uses the '[CNullAssetTxData::IsValid()](https://github.com/RavenProject/Ravencoin/blob/master/src/assets/assets.cpp#L4507)' function again, it could be a problem, right?

**Comment by jeroz1** [comment]
> were making sure that logic even needed to exist.

Wouldn't we need a re-evaluation from ISE if the logic was removed entirely? Since they have not tested the code without it.

**Comment by hans-schmidt** [comment]
The function CNullAssetTxData::IsValid() is never used, so there is no doubt that changing || to && on line 4520 of "assets/assets.cpp" as ISE suggested will have absolutely no effect on code functionality.

The more important and more difficult question is whether CNullAssetTxData::IsValid() never being called is an oversight which causes the checks in that function to never take place in places where they are needed. 

The only significant class functions CNullAssetTxData::ConstructTransaction() and CNullAssetTxData::ConstructGlobalRestrictionTransaction() are called only in the file "rpc/rawtransaction.cpp". In that file in lines 1354 to 1462, asset name validity is implicitly checked when asset name existence is explicitly checked, and asset type is explicitly checked where appropriate. Flag status is not checked in that code block and does not need to be since the tag values are set as needed upon CNullAssetTxData class instantiation in lines 1394 and 1431 and 1459. The flag values are later checked as needed during verification operations using the VerifyNullAssetDataFlag() function.

So at first inspection, it appears that the CNullAssetTxData::IsValid() function is not needed and the bug is irrelevant.

**Comment by fdoving** [comment]
Merging the fixed check will not have any negative effects.
I suggest merging this change.

If functions are to be removed, make own PRs for that.
Having unused broken functions is worse than having unused functions.

ACK 01189fd68f866e86d394cc2d6681d6003db205e8

**Comment by ravenlandpush** [comment]
As hans-schmidt suggested ISE-RAVEN-2020-02 claimed that the evaluation was wrong using || instead of &&, so changing this should not require resubmission to ISE as this has already been evaluated the correct validation routine providing nothing else was changed relating to this function. HOWEVER:

As hans-schmidt alludes, is CNullAssetTxData::IsValid() never being called by intent or something more? Inspection of ISE-RAVEN-2020-02 and previous bugs identified the issue relating to issues caused by crafting rawtransaction that resulted in this function or others always returning true, which had consequences.

If CNullAssetTxData::IsValid() is not used, never will be used, and is not required, then should it not be removed altogether? I agree, that leaving a potential break in a validation routine even if unused, that may be forgotten along the road is also not an ideal long term solution in the weight of probability that allows it to be potentially used again innocently or accidentally as unlikely as it may be, again consequences. Even in such a case the ISE recommendations were to make the change committed in this PR. It should be okay, but should it be in core if the code is not used? I say no.

So adequate caution and conscientiousness is expressly warranted given potential consequences and previous experiences of each case, why I can understand spyders perspective in terms of not pushing this change if unnecessary.

I understand from the above comments of others that CNullAssetTxData::IsValid() is no longer utilized due to changes elsewhere in the source, this somewhat is making the bug in the ISE irrelevant and therefore this commit. So unless there is a true need for this function in core in the future, or this function actually should be implemented elsewhere, this really comes to a case of keeping the function or not than anything else and the implications of each.

I agree having unused broken functions is bad, but propose that perhaps committing or keeping unnecessary or unused function to core may be only marginally more ideal, and if it can be eliminated safely it should be as it would in itself prevent confusion or potentially even the same bug or practice of arising in the future that brought ISE-RAVEN-2020-02 or other rawtransaction bug around to begin.

 This is not a case of if it is not broke do not fix it, we know its broke, it is a case of whether to include unused code in core. Unless I am missing something? Which very well may be possible after a long time away.

Best,
Adam

**Comment by HyperPeek** [comment]
Ok, so maybe delay merging and rather make a PR to remove it altogether once evaluated? then we close this PR along with it.

**Pull request merged**
