### PR TITLE
Update to build-ubuntu.md (PR #964)

### PR DESCRIPTION
**Pull request by jeroz1**
- Added Ubuntu 18.04 dependencies
- Fixed an issue with quotation marks

### CODE REVIEW

**Review by fdoving — APPROVED** [review]
ACK c2619c537d503429e3a7c58913ed82279664718b

**Comment by fdoving** [comment]
Direct link to the updated version of the file: 
https://github.com/jeroz1/Ravencoin/blob/develop/doc/build-ubuntu.md

**Review by HyperPeek — APPROVED** [review]
Approved c2619c537d503429e3a7c58913ed82279664718b

**Comment by jeroz1** [comment]
Someone else just ran into the same issue while trying to build. Any reason why this is still open?

**Comment by fdoving** [comment]
Needs approver+merge.

**Comment by Scotty0448** [comment]
The same quotation marks should also be removed from line 249 of /contrib/install_db4.sh.

**Comment by fdoving** [comment]
> The same quotation marks should also be removed from line 249 of /contrib/install_db4.sh.

I don't think that is needed. 
The variable will be set to the path at this point.

It will `echo` something like this: `export BDB_PREFIX='/home/user/src/db4'`

**Comment by Scotty0448** [comment]
> I don't think that is needed.
> The variable will be set to the path at this point.
> 
> It will `echo` something like this: `export BDB_PREFIX='/home/user/src/db4'`

Right, the variable will be set, but it should echo it without the quotes like this: `export BDB_PREFIX=/home/user/src/db4`

**Comment by fdoving** [comment]
> > I don't think that is needed.
> > The variable will be set to the path at this point.
> > It will `echo` something like this: `export BDB_PREFIX='/home/user/src/db4'`
> 
> Right, the variable will be set, but it should echo it without the quotes like this: `export BDB_PREFIX=/home/user/src/db4`

I think that will break with one whitespace.

**Comment by Scotty0448** [comment]
> > > I don't think that is needed.
> > > The variable will be set to the path at this point.
> > > It will `echo` something like this: `export BDB_PREFIX='/home/user/src/db4'`
> > 
> > 
> > Right, the variable will be set, but it should echo it without the quotes like this: `export BDB_PREFIX=/home/user/src/db4`
> 
> I think that will break with one whitespace.

I see what you meant now. Without the variable the quotes are no longer a problem and actually needed in some cases like you point out.

**Comment by hans-schmidt** [comment]
Approved

**Pull request merged**
