### PR TITLE
Added missing command to cross-compile ARM

### PR DESCRIPTION
**Pull request by jeroz1**

### CODE REVIEW

**Comment by cfrogjump** [comment]
@jeroz1 Change the PR to be against develop and we'll get it merged in.

**Comment by jeroz1** [comment]
Done :+1:

**Comment by cfrogjump** [comment]
@jeroz1 I think the change to the develop branch is pulling in far more than intended. Maybe rebase your branch and create a new pull request?

**Comment by jeroz1** [comment]
Lol, ok then it was not just me. I already thought: what is all this stuff?

**Pull request closed without merging**
