### PR TITLE
Add Wallet Repair tab to the debug window

### PR DESCRIPTION
**Pull request by Scotty0448**
This adds a Wallet Repair tab to the debug window. It also adds a Wallet Repair menu item to the Help menu. The general functionality was extracted from a similar implementation in Dash.

The repairs are accomplished by automatically restarting Raven Core with one of three options: rescan, zapwallettxes=1 or reindex.

### CODE REVIEW

**Comment by jeroz1** [comment]
I have tested this on Ubuntu and Windows. The -reindex function has a nice warning window. 

Screenshot from 2019-04-14 17-36-38
Screenshot from 2019-04-14 17-38-33

**Comment by ravenlandpush** [comment]
great work scotty this is great!

**Comment by jeroz1** [comment]
How about a button that opens the blockchain folder? People often have problems finding it because it’s hidden by default. Is that easy to add?

**Comment by ravenlandpush** [comment]
> 
> 
> How about a button that opens the blockchain folder? People often have problems finding it because it’s hidden by default. Is that easy to add?

There are a few differences from OS to OS but its essentially just a shell(%appdata%/raven) or shell(~/.raven) on linux systems, so shouldn't be too difficult to do.


Best,
Adam

**Comment by jeroz1** [comment]
I found this: https://stackoverflow.com/a/3546503

But let’s first get this approved before adding new code.

**Pull request merged**
