### PR TITLE
Fix dependencies and build workflows.

### LINKED ISSUE #902: Dependencies for build pipeline not available - Fix build pipeline
There are dependencies that are not available.

Fix build pipeline.

### PR DESCRIPTION
**Pull request by fdoving**
Fixes #902 

- Disables AWS links and uploads.
- Forces always building of depends.
- Can we trust the OSX-sdk-link?
- Includes PR #896 (tests failed without it)

### CODE REVIEW

**Comment by fdoving** [comment]
Sorry about the open/close. Was messing with the android app. 🤦 .

**Comment by TronBlack** [comment]
This is great, and exactly what was needed.  I'll bring up approvals and GitHub rules in the dev meeting tomorrow.  We need to get a set of developers to help approve code merges.  The code checks not working was stopping that conversation, first the test "bug" or expiration, then the dependencies.  This PR unblocks that and puts us back on track.

I do have some questions about the dependencies and their source.

**Comment by fdoving** [comment]
I also question the source of the OSX SDK. I just found it online to make it build.
Maybe someone the project trusts can get the OSX SDK from a reliable source and host on ravencoin.org or somewhere the project trust?

**Review by kentbull — COMMENTED** [review]
Nice work. I'd like to understand the Github scripts and the https://github.com/shannon1916/MacOSX10.11.sdk.tar.gz repo.

Also, what is the logic behind the change from `1607731200` to `1907731200`?

**Comment by kentbull** [comment]
Reading #896 answered my question: Updated julian time beyond Dec 2020 to mid-year 2030
This PR looks good to me.

**Review by kentbull — APPROVED** [review]

**Review by TronBlack — APPROVED** [review]
With the caveat that shortly we move the Mac SDK dependency to the RavenProject

**Comment by underdarkskies** [comment]
That SDK should not be publicly hosted. And therefor can’t be referenced in any script from a public location. Apples rules, not mine. To download a copy you can sign up for a free dev account and agree to their ToS

**Comment by underdarkskies** [comment]
> That SDK should not be publicly hosted. And therefor can’t be referenced in any script from a public location. Apples rules, not mine. To download a copy you can sign up for a free dev account and agree to their ToS

They specifically disallow redistribution

**Comment by kentbull** [comment]
> > That SDK should not be publicly hosted. And therefor can’t be referenced in any script from a public location. Apples rules, not mine. To download a copy you can sign up for a free dev account and agree to their ToS
> 
> They specifically disallow redistribution

Thanks for mentioning this. There are 8461 files in that SDK, thus a high number of potential attack vectors. We'll want to get a trusted pipeline set up in the future. Ideally we could replace that dependency at some point with something else.

**Review by kentbull — APPROVED** [review]

**Review by TronBlack — APPROVED** [review]

**Review by HyperPeek — APPROVED** [review]
Looks good -- OSX needs more thoughts as discussed. Manual workflow for testing build-ability from time-to-time is fine for me at this point.

**Review by alisscco — APPROVED** [review]

**Comment by fdoving** [comment]
Branch protection rule requires an admin to remove osx from the list of checks to pass. Write access is not enough.
https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by HyperPeek** [comment]
I rather merge this "as is" (no squash) to not risk any more issues.

**Pull request merged**
