### PR TITLE
gui: osx darkmode

### PR DESCRIPTION
**Pull request by fdoving**
Issue #1005

### CODE REVIEW

**Comment by HyperPeek** [comment]
If anyone can confirm this works I am happy to approve. I cant check on OSX myself atm.

**Comment by jeroz1** [comment]
works

Screenshot 2021-05-30 at 20 10 04
Screenshot 2021-05-30 at 20 09 50

**Review by HyperPeek — APPROVED** [review]
approved ba5e83c047439251317d7a43aad16fb0fca3ebbb

**Comment by hans-schmidt** [comment]
Approved

**Pull request merged**
