### PR TITLE
Updated julian time beyond Dec 2020 to mid-year 2030

### PR DESCRIPTION
**Pull request by TronBlack**
The hard-coded static date caused an rpctest issue.

### CODE REVIEW

**Comment by fdoving** [comment]
Looks good to me.

Maybe the test could print a warning if less than X-time until this needs to change again?
Hardcoded date/time is a pain.

**Review by fdoving — APPROVED** [review]

**Comment by hans-schmidt** [comment]
This PR is no longer needed. The same changes are included as part of PR#904

**Comment by hans-schmidt** [comment]
This PR is no longer needed. The same changes are included as part of PR#904

**Comment by hans-schmidt** [comment]
This PR is no longer needed. The same changes are included as part of PR#904

**Comment by alisscco** [comment]
I see that they were ok the first time , please don’t alter .

**Pull request closed without merging**
