### PR TITLE
Depends: Update Qt 5.12.10, openssl 1.1.1k and most of the dependencies. (This is 910 for develop-sig, squashed)

### PR DESCRIPTION
**Pull request by fdoving**
Depends: Qt5 5.12.10 and openssl 1.1.1k
Depends: libevent updated to 2.1.11 (Changes copied from bitcoin).
Depends: bdb download from https.
Depends: Download fontconfig with https.
Depends: native_ds_store 1.3.0 (Copied from bitcoin).
Depends: Update native_libdmg-hfsplus (Copied from bitcoin).
Depends: Update native_mac_alias to 2.1.1 (Copied from bitcoin).
Depends: Update zeromq to 4.3.1 (Copied from bitcoin).
Depends: boost 1.71.0.

       Most of this is copied from bitcoin. (Thanks!)

raven-qt: Add QMacStyle to raven.cpp

Build: Disable shared libraries when building for Windows.
       Mingw32 does not like it. And I can't figure it out.

Build/depends changes:
    - openssl cross compile for osx requires this new version of clang.
    - most build-scripts in depends/ are updated from bitcoin.
    - depends/Makefile tuned to not break the paths.
    - path-changes in openssl.mk to reflect the not broken paths.
    - git build: scripts tuned to work with SDK .tar.gz in /tmp/SDKs.
    - git build: default to python3.
    - python-is-python3 added to depends.

### CODE REVIEW

**Comment by fdoving** [comment]
Not test-built.

picked+squashed version of PR #910 for develop-sig.

**Review by HyperPeek — APPROVED** [review]

**Review by alisscco — APPROVED** [review]

**Review by ben-abraham — COMMENTED** [review]
I would suggest moving the hardcoded URL value from `OptionsDialog::on_thirdPartyTxUrlsReset_clicked()` and `void OptionsModel::Init(bool resetSettings)` to a default constant somewhere.
I'm not sure if there is a great place for those kind of default constants anywhere currently.

**Comment by fdoving** [comment]
I agree on the constant.
We have [src/qt/guiconstants.h](https://github.com/RavenProject/Ravencoin/blob/master/src/qt/guiconstants.h)
Could probably put it there.

As this currently is merged, it will require a new PR.
If not done shortly, we could create a issue, for reference.

**Review by ben-abraham — APPROVED** [review]
utACK

Code changes look good, build changes are pretty heavy but all looks good 👍 

Commit: 9cd27c1dc6c949a05de0b9e3d28d2102fb8a4e51

**Pull request closed without merging**
