### PR TITLE
gui: option to hide text in toolbar

### LINKED ISSUE #478: menu toggle
add a toggle option to only show menu icons to save space and make it cleaner when in smaller window size as some things gets distorted.

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

### PR DESCRIPTION
**Pull request by fdoving**
Add option to only show icons in toolbar.

Closes #478

### CODE REVIEW

**Comment by fdoving** [comment]
https://github.com/RavenProject/Ravencoin/issues/478#issuecomment-848241956

**Review by HyperPeek — APPROVED** [review]
Nice option, approved 42cdbd1ae0618f70d1af540f2bd799ecab058e09

**Comment by fdoving** [comment]
Latest commit changes it to not require restart.

Should be squashed if merged.

**Comment by fdoving** [comment]
Rebased. Commit f2aa67cff9b8f1da46c9f4d020d08c48219b6391

**Comment by hans-schmidt** [comment]
Approved

**Pull request merged**
