### PR TITLE
Create .devcontainer/devcontainer.json

### PR DESCRIPTION
**Pull request by CrashKharma**
"1st COMMIT

### CODE REVIEW

**Comment by jeroz1** [comment]
I think you started pushing changes to the wrong repo.

**Comment by CrashKharma** [comment]
Thank you,jeroz1  im teaching myself so it probably wont be be my last
mistake. Im trying to run raven, i had it syncing and could see  my wallet,
im pretty sure i was running it in full node mode. I just want to run it in
light mode.   I got confused by all the files & folders still working on
understanding what ext.'s do what. Keith

**Comment by mostafa09127286242** [comment]
Pashaman

**Comment by hans-schmidt** [comment]
The submitter created this PR by mistake. I am closing it.

**Pull request closed without merging**
