### PR TITLE
Create descriptor.cpp *Taproot*

### PR DESCRIPTION
**Pull request by corviato1**
Basic Taproot signing support for descriptor wallets.
https://github.com/bitcoin/bitcoin/pull/21365/files

### CODE REVIEW

**Comment by HyperPeek** [comment]
As these PR's are made they do not compile -- they depend on each other and even if merged together I am not sure. 
I am happy to discuss the need / benefit of Taproot here or on discord, but at this point I would rather look into adding segwit fully back to the code first, which may be a requirement for Taproot anyway.

**Comment by corviato1** [comment]
Hi HyperPeek, yeah it's an uphill job.  Kinda in over my depths.  Still, I see the value of Taproot and would like to see RVN push the code since BTC pretty much already has.  There is no good reason for it not to be pushed in with the next fork.   Any help you can give on that(including merging segwit) would be much appreciated.   When is the next voice dev meeting in discord?

**Comment by fdoving** [comment]
NACK - can't do it this way.

**Comment by corviato1** [comment]
> NACK - can't do it this way.

What way should it be done?

**Pull request closed without merging**
