### PR TITLE
ShirinGhaderi

### PR DESCRIPTION
**Pull request by ShnQdr**
ShirinGhaderi

### CODE REVIEW

**Comment by blondfrogs** [comment]
These commits are already in the develop branch. Was there a reason you wanted to put them in again?

**Comment by blondfrogs** [comment]
I would like to close this PR. It is trying to commit duplicate commits that are already in the branch. @TronBlack Can we close this?

**Comment by TronBlack** [comment]
I checked that the changes are in develop by checking each file and seeing the coinbase and version update, but if you do a compare:
https://github.com/RavenProject/Ravencoin/compare/develop
It shows differences.  Is there an explanation for this?

**Comment by ShnQdr** [comment]
Like

**Comment by spyder46n2** [comment]
We have a newer PR that includes this and other changes different between master-dev. Thanks!

**Pull request closed without merging**
