### PR TITLE
consensus: correct verification of transactions pre p2sh-asset activation

### PR DESCRIPTION
**Pull request by fdoving**
correct verification of transactions pre p2sh-asset activation

### CODE REVIEW

**Comment by fdoving** [comment]
Commit 1cc40a1 synced mainnet without issues.

Restarting a sync with commit 58fbe23

**Comment by fdoving** [comment]
To make it cleaner, drop the additional overload and use biranmcts suggestion.
A default argument makes sense on nP2Active, it is the last argument, and it is not a reference.

**Comment by fdoving** [comment]
Squashed and rebased. 389ae55fa09a185e3cf6bf3974cc00f1a9ba3ba2

**Review by HyperPeek — APPROVED** [review]
After another week of testing I am confident this is a fix for the sync issue on mainnet as well as a less restrict check before activation on mainnet. We need this fix for a new testversion that allows testing on both, Test and mainnet. Approved 389ae55fa09a185e3cf6bf3974cc00f1a9ba3ba2

**Comment by fdoving** [comment]
@TronBlack Could you have a look at this?

**Comment by hans-schmidt** [comment]
Approved

**Pull request merged**
