### PR TITLE
gui: Manage assets - update list when shown.

### LINKED ISSUE #1059: Restricted Asset: Can't be re-issued until the wallet was closed and re-opened
After creating a restricted asset, it does appear in the asset list of the wallet after some time. When trying to re-issue it under "Manage Assets" it will not appear in the list.
After closing / re-opening the wallet, the asset can be managed as usual.

### PR DESCRIPTION
**Pull request by fdoving**
Update asset list when the qcombobox is shown.
    Fixes #1059

### CODE REVIEW

**Comment by fdoving** [comment]
I have seen this too.

If you check the debug-window, I think this is corrected once the transactions leaves the mempool.
They should show up in the Overview and on Manage Assets at the same time.

**Comment by HyperPeek** [comment]
Testnet was probably slow. Will keep an eye on it. The restricted asset was definitely in the list after some time, so it should be fixed.

**Review by HyperPeek — APPROVED** [review]
Tested and works, approved 08956b13efbff7478d5169150a3fe971e6c92984

**Comment by hans-schmidt** [comment]
Approved

**Pull request merged**
