### PR TITLE
Backport of Bitcoin Core PR13604 and PR13750 to add 32-bit arm support for Raven-qt

### PR DESCRIPTION
**Pull request by jeroz1**
Because.... it works? 😄 

```
cd depends
make HOST=arm-linux-gnueabihf -j4
cd ..
./autogen.sh
./configure --prefix=$PWD/depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++
make
```

### CODE REVIEW

**Comment by jeroz1** [comment]
2019-09-24-173452_1920x1080_scrot

**Comment by ravenlandpush** [comment]
I'm wondering why this didnt make it into https://github.com/RavenProject/Ravencoin/releases/tag/v3.3.0 for the ARM build which I discovered when adding support to RavencoinOS for this latest binaries.

 To my disappointment it means I will have to merge it and test it thoroughly. Hopefully this can make it into the later build releases for ARM. As jeroz patch is a good'n.

Cheers jeroz!

- push

**Comment by ravenlandpush** [comment]
I believe this can be fixed by using the following within the build template

```
./autogen.sh
CONFIG_SITE=$PWD/depends/arm-linux-gnueabihf/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --enable-glibc-back-compat --enable-reduce-exports --disable-bench --disable-gui-tests CFLAGS="-O2 -g" CXXFLAGS="-O2 -g" LDFLAGS="-static-libstdc++"
```

image

**Comment by cfrogjump** [comment]
@ravenlandpush, you are correct. The configure needs to be changed for the build. I'll get the change in and generate binaries on Monday, they won't be part of this release but I can let you know where to grab them.

**Comment by aziouk** [comment]
Thanks man I appreciate it. For the official RavencoinOS image I would certainly prefer that (and I am sure so would many of the people running it!), at least then the source and testing is not guaranteed from us. Not that I don't mind doing it. It just seems best practice.

Thanks again!

Best,
Adam

**Pull request merged**
