### PR TITLE
Put the how-to md files front and center for novice users

### PR DESCRIPTION
**Pull request by kralverde**
It seems many users don't know what to do when accessing the Ravencoin repo. This is a trivial commit. Should I create some sort of how-to index file linking to respective md files in docs?

### CODE REVIEW

**Review by fdoving — APPROVED** [review]
ACK e8e1682388483294c794d7d87a0d049438d15e51

**Review by TronBlack — APPROVED** [review]

**Review by HyperPeek — APPROVED** [review]

**Comment by fdoving** [comment]
Build checks ignore .md files - only admins can merge with the protection rules set like this.
There is no need to rebuild everything with only text/doc/.md changes.

**Comment by fdoving** [comment]
Something like this could fix our issue: https://github.com/marketplace/actions/skip-duplicate-actions

**Comment by fdoving** [comment]
I made #1078 to work around this issue.

**Comment by hans-schmidt** [comment]
Close and re-open to trigger checks using the new Actions yaml

**Comment by fdoving** [comment]
Base changed to develop.

**Comment by jeroz1** [comment]
Trivial and approved change. Merge?

**Review by TronBlack — APPROVED** [review]

**Comment by jeroz1** [comment]
Looks like this PR got into develop via a different route: https://github.com/RavenProject/Ravencoin/commit/9f28c26281fd2c9463b5ceef9332d905ef081df6, leaving the current PR with 0 changes to the code.

**Pull request merged**
