### PR TITLE
Bip39: Add support multilanguage

### PR DESCRIPTION
**Pull request by henry-arcu89**
The [Ravencoin Wallet for Android](https://github.com/RavenProject/ravenwallet-android) use the system language to create the seed words. In my case, this app generated the seed words in Spanish.

The official [Ravencoin Wallet for Windows, Linux & Mac](https://github.com/RavenProject/Ravencoin/) only support import seeds in English language. Therefore, I cannot import my seeds in Spanish of my Android wallet to my PC wallet.

Futhermore, the [BIP39 tool for Ravencoin](https://ravencoin.org/bip44/)  also can generate seed words in these languages: English, Spanish, French, Japanese, Chinese simplified, Chinese traditional, Korean and Italian.

The [app for Android](https://github.com/RavenProject/ravenwallet-android), only generate in English, Spanish, French, Japanese and Chinese (I believe is it the simplified).

With this Merge Request I add support for import and generate in GUI from all languages supported by [BIP39 tool for Ravencoin](https://ravencoin.org/bip44/): English, Spanish, French, Japanese, Chinese simplified, Chinese traditional, Korean and Italian.

By default, if not pass language for generate words, it generates by default language in English.

When check if the words are valid, if not pass the language, it detects the language words checking all word lists.

I add a new test in python, in /test/functional/wallet_bip44_multilanguage.py for testing the new functions. 

For now, it passes the test wallet_bip44_multilanguage.py and wallet_bip44.py. I don't know how use the test for GUI in C++, but I believe that is all correct, because in the GUI everything seems to work properly.

If I have time, I will try to add the functionality so that it can be generated in languages other than the default from the RPC console with commands.

I added a warning in Japanese, because the [BIP39 tool for Ravencoin](https://ravencoin.org/bip44/) generate the seed words separated by ideographic space, and in the GUI we use only standard spaces. For now, I can't the way to replace de ideographic space by standard space in C++

If you want, can check if everything works correctly or you can also add some extra function.

KAAAW!

### CODE REVIEW

**Comment by HyperPeek** [comment]
Thanks for adding this -- good work! Initial quick scan through the files looks good, will do some more tests.

**Comment by henry-arcu89** [comment]
It would be very good if it could be tested in different languages and OS, to verify that it worked correctly, and that there wasn't encoding error of the special characters when copying the words.

**Comment by hans-schmidt** [comment]
Thank you for your work on this!
Examination of the code looks good.
Brief testing was successful.
Users of the non-English word lists are encouraged to do their own testing using this and other wallets.
Approved.

**Comment by kralverde** [comment]
Japanese does not work; japanese (and other languages) use U+3000 for spaces. The string may need to be cleaned.

image

**Comment by kralverde** [comment]
Yes, replacing the ideographic space with a normal space let it work

**Comment by kralverde** [comment]
I went through all iterations of 12-25 words of the accepted languages and they all generated the correct addresses (including the japanese when swapping out the spaces). Did not test bip39 passphrases thoroughly.

**Pull request merged**
