### PR TITLE
GUI: Add Wallet -> Get my words (PR #976)

### PR DESCRIPTION
**Pull request by fdoving**
Add the menu item and show the words and passphrase in simple messagebox.
    Closes Issue #975

### CODE REVIEW

**Comment by chainstrap** [comment]
Nice

**Review by HyperPeek — APPROVED** [review]
Nice feature, straight forward implemented. Approved.

**Comment by fdoving** [comment]
#975 for screenshots.

**Comment by hans-schmidt** [comment]
-Nice new feature. It was available in the console using "getmywords", but this is easier and safer for most people.
-I didn't test the locking feature, but I tried it on a wallet which was not encrypted and the locking attempt caused no trouble.

Approved

**Pull request merged**
