### PR TITLE
Qt: Added combobox to header to select price unit.

### PR DESCRIPTION
**Pull request by ben-abraham**
Added an easily-extensible ComboBox to the main wallet display, to change the unit of the previewed price.

Available conversions are defined in an array for easy modification if needed, or for more reference currencies in the future.
```
const RavencoinPriceDisplay priceUnits[4] = {
        {"BTC / RVN", "RVNBTC", 1},
        {"mBTC / RVN", "RVNBTC", 1000},
        {"µBTC / RVN", "RVNBTC", 1000000},
        {"USDT / RVC", "RVNUSDT", 1}
};
```

Small patch to give back to the community :)

Before:
image

After:
image

### CODE REVIEW

**Comment by fdoving** [comment]
Cool. I merged it to my fdov-develop branch for testing.

Satoshis would be nice.

I'm not sure about the BTC / RVN label for the dropdown.. Could ' / RVN' be removed from those?

**Comment by ben-abraham** [comment]
> Satoshis would be nice.
Easy :) I will commit this shortly.
 
> I'm not sure about the BTC / RVN label for the dropdown.. Could ' / RVN' be removed?
Also simple, I considered this originally but mostly wanted to stick to how it was originally displayed.

**Comment by fdoving** [comment]
I don't have strong feelings about the label, just throwing it out there.

I also noticed it does not write it's state anywhere, it will return to BTC on restarts.
Adding it to settings would be a nice improvement.

**Comment by ben-abraham** [comment]
I agree on the settings, it'd be nice to have it remember. I'll finish up that tomorrow, I started it but it didn't quite save the way I was expecting.

**Comment by ben-abraham** [comment]
Alright! Just finished the last few fixes and it's looking good now. I made the homescreen combobox saved/remembered, and added the option to the settings screen itself as well.

image

**Comment by fdoving** [comment]
Looking good!

**Review by alisscco — APPROVED** [review]
Sorry was a lil bit occupied..

**Comment by ben-abraham** [comment]
> Sorry was a lil bit occupied..

No worries at all! I ended up catching a bug anyway :)

**Review by HyperPeek — APPROVED** [review]

**Review by alisscco — APPROVED** [review]

**Pull request closed without merging**
