### PR TITLE
Correct Ravencoin's Commit History

### PR DESCRIPTION
**Pull request by underdarkskies**
This is a Large PR that adds the missing commits between July 7th and October 26th(raven's true fork date)
I rebased this branch to Bitcoin's:
#d93fa26  Merge #11490: Disconnect from outbound peers with bad headers chains 
then cherry-picked all raven commits back in, minus the merge commits(Duplicative) 

This corrected history is invaluable for future rebasing and merging with bitcoin, so that developers can see which commits are included in Ravencoin currently.

However, due to the rebasing processes, all of Raven's commit SHA's are now different, and this will impact remote branches as well as any development branches not based off of the correct history.

until this is rectified, i would recommend possibly storing this branch separately from Master, until impact can be mitigated.

### CODE REVIEW

**Comment by blondfrogs** [comment]
@underdarkskies What do you want to do with all these merge conflicts?

**Comment by underdarkskies** [comment]
@blondfrogs to be perfectly honest im not sure why github shows so many conflicts. it must be due to the rebaseing procedure. Ideally all I want to do is to rebase ravencoin master and all other branches to the correct bitcoin fork commit #d93fa26. this is something you could attempt in a dev lab with a separate branch. It would need to be done completely and contributors would need to be notified has all shas of each of ravencoins commits will change. its a fresh clean start. but it displays the missing commit history if done properly.

**Comment by underdarkskies** [comment]
steps to create:
1)fork a bitcoin repo and bring it to the relevant commit with git reset --hard d93fa261f079d529a94ff26aa406a49e28d10340
2)switch to ravencoin repo
3)add that repo as a upstream1 remote to ravencoin
4)git pull --rebase upstream1 master

**Comment by underdarkskies** [comment]
spent a long time cleaning this up with comparative git diffs against master along the way. this has been superceded by #159 so i will close this out for now

**Pull request closed without merging**
