### PR TITLE
Update secp256k1 from upstream.

### PR DESCRIPTION
**Pull request by fdoving**
Updated from https://github.com/bitcoin-core/secp256k1
    At commit cc2c09e3a7808311ed46db203c4fd1b75012c982

Copied over and test built.

Have not done more local tests, yet.
Putting it here to get test help and reviews/feedback.

### CODE REVIEW

**Review by alisscco — APPROVED** [review]

**Review by HyperPeek — APPROVED** [review]
Its an update and looks like 1:1 from bitcoin, so approve.

**Review by alisscco — APPROVED** [review]

**Comment by fdoving** [comment]
I propose we wait for bitcoin to merge their PR 21573.
Then we can get all their tweaks in one go.

**Comment by HyperPeek** [comment]
> I propose we wait for bitcoin to merge their PR 21573.
> Then we can get all their tweaks in one go.

Ok -- if we decide to go for a p2sh build we can leave this for a bit later. Just requires additional testing then later.

**Comment by fdoving** [comment]
As this has not been approved for bitcoin. We decided to go with the version from current bitcoin/master. 
Closing.

**Pull request closed without merging**
