### PR TITLE
Doc: Add build-ubuntu.md (PR #935)

### PR DESCRIPTION
**Pull request by fdoving**
Detailed step-by-step instructions on how to build
    from git on Ubuntu 21.04 Hirsute Hippo.

Depends on #934 to work.

### CODE REVIEW

**Review by HyperPeek — APPROVED** [review]

**Comment by hans-schmidt** [comment]
We may want to change this to Ubuntu 18.04 with a warning about the GLIBC version reverse compatibility problem if built on a newer Ubuntu version.

**Comment by fdoving** [comment]
> We may want to change this to Ubuntu 18.04 with a warning about the GLIBC version reverse compatibility problem if built on a newer Ubuntu version.

I agree.

**Comment by fdoving** [comment]
Need to have a look at the package names, it might be slight differences from 18.04.
I still think this can go in unchanged, for now.
It is way better than what is there today, and it specifies how to build on that version of Ubuntu.

We can make an issue on updating with more versions and distros etc.

**Comment by HyperPeek** [comment]
I suggest we merge and make another PR. I agree that this is way better than what we have now and its actually ok for 21.04

**Pull request merged**
