### PR TITLE
Extended RPC to support Insight-API

### PR DESCRIPTION
**Pull request by underdarkskies**
This PR adds additional address, spent and timestamp indexes, as well as includes p2pk transactions into the address index.
 It does however revert:
- "Merge #11167: Full BIP173 (Bech32) support"  …
- "Rename out to m_tx_out in CScriptCheck"  …
- "Merge #10953: [Refactor] Combine scriptPubKey and amount as CTxOut in CScriptCheck

Ideally the indexes could be added without reverting these commits, as they do offer groundwork for full segwit compatibility

These rpc calls would be very helpful to natively include in the project, or at least a stable explorer branch of the codebase if there are performance performance considerations that prevent them from being included in the master branch.

### CODE REVIEW

**Comment by underdarkskies** [comment]
I cleaned up this PR a bit today.

**Comment by cfox** [comment]
We merged this into our current develop branch and got a compile error.  Can you merge our develop branch and check?  (We hope to have auto-builds for PRs soon)

```
test/test_raven.cpp:73:22: error: no matching constructor for initialization of 'CBlockTreeDB'
    pblocktree = new CBlockTreeDB(1 << 20, true);
```

**Comment by cfox** [comment]
It is compiling now and seems to run ok (although I didn't test the extended functionality).  I am concerned that the base58 tests fail though:
`src/test/test_raven --run_test=base58_tests`
`*** 49 failures are detected in the test module "Raven Test Suite"`

**Comment by underdarkskies** [comment]
I'll add those test commits, looks like 11167 just changed the test structure and the base58 valid/invalid json key structure

**Comment by underdarkskies** [comment]
this has been superseded by PR #131

**Pull request closed without merging**
