### PR TITLE
Updated Copyright Year Using Python Dev Tool

### PR DESCRIPTION
**Pull request by Brock-Wood**
I updated all of the copyright years using /contrib/devtools/copyright_header.py

### CODE REVIEW

**Review by fdoving — APPROVED** [review]
ACK f318d92d6642f81d0d095141bc0e07f2a913548f

**Review by HyperPeek — COMMENTED** [review]
I assume the year picked (2020 / 2021) depends on the last change of the file?
I am not sure why the diff of currencyunits.h shows up as entirely changed although its not. No problem, just wondered.

**Comment by fdoving** [comment]
> I assume the year picked (2020 / 2021) depends on the last change of the file?
Yes.
https://github.com/fdoving/Ravencoin/blob/0b368bb433e6b44b9500e5deb6ad8642e6dd63d5/contrib/devtools/copyright_header.py#L423

> I am not sure why the diff of currencyunits.h shows up as entirely changed although its not. No problem, just wondered.
Same. I did not find anything changed.

**Review by HyperPeek — APPROVED** [review]
Approved f318d92d6642f81d0d095141bc0e07f2a913548f

**Review by hans-schmidt — APPROVED** [review]
Trivial change to comment text only.
Approved

**Pull request merged**
