### PR TITLE
gui: add version to modal overlay

### PR DESCRIPTION
**Pull request by fdoving**
Add version with commit hash.
Easier to help people with sync issues.

image

### CODE REVIEW

**Comment by HyperPeek** [comment]
Perfect -- I really like this! Will approve once build-check is back.

**Comment by fdoving** [comment]
Rebased. Commit 5aee68a

**Review by HyperPeek — APPROVED** [review]
Approved 5aee68a57c898d77ef5f43ba3250a52ac1268722

**Comment by hans-schmidt** [comment]
Definitely a good idea. Approved

**Pull request merged**
