### PR TITLE
Add open in blockexplorer contextmenu option

### PR DESCRIPTION
**Pull request by LufyCZ**
Sorry for the PR spam

### CODE REVIEW

**Comment by jeroz1** [comment]
Thanks! And no worries, it happens more often.

**Comment by jeroz1** [comment]
@spyder46n2 @cfox this addresses #797

**Review by TronBlack — APPROVED** [review]
Thank you for your contribution.

Future improvement: Allow selection of explorer.   Use %address% or something similar to replace the address.  Like https://someexplorrer.com?address=%address%

**Comment by TronBlack** [comment]
Looks like there was a build failure in our automated build process.  Please hit details and see what else is needed.  It may be operating system specific.

**Comment by jeroz1** [comment]
I built and tested this on linux and windows. Works fine for me. The only issue I see is the choice of explorer. Afaik, there are three explorers that support both assets and RVN transactions: 

- https://rvn.cryptoscope.cc/, closed source, has full asset support, and an active community developer.
- https://api.ravencoin.org/, open source, is asset aware but users can not search for assets. 
- https://explorer.ravenland.org/, closed source, has full asset support but has no active community developer. 

My personal preference is option 1.

**Comment by jeroz1** [comment]
LOL, nobody cared to mention that this functionality is already hidden in the wallet!? 

Wallet > Options > Display > "Third party transaction URLs"
Example: `https://rvn.cryptoscope.io/tx/?txid=%s`

When filled out, right click a transaction and find an extra option at the bottom of the pop-up menu. 

I think, we need to have a link in this pop-up menu saying "Set default block explorer", which opens Wallet > Options > Display. And change "Third party transaction URLs" to "Set block explorer transaction URL".

**Comment by fdoving** [comment]
Could setting a default in Wallet > Options > Display > "Third party transaction URLs" and have a dropdown of presets be an option?

**Comment by jeroz1** [comment]
> Could setting a default in Wallet > Options > Display > "Third party transaction URLs" and have a dropdown of presets be an option?

No, I am not a fan of that. It would favor the "default" third party over any other. People should really set this themselves imho. It just needs to be more obvious and not hidden away.

**Pull request closed without merging**
