### PR TITLE
contrib: Dockerfile updated

### PR DESCRIPTION
**Pull request by fdoving**
Use Ubuntu 20.04.
    Drop outdated bitcoin-ppa.
    Build Berkeley DB 4.8 from source with install_db4.sh.

    Usage: 'docker build -t ravencoin:4.7 -f contrib/Dockerfile .'

### CODE REVIEW

**Review by HyperPeek — APPROVED** [review]
Version updates for docker, approved fb1df9b39ebc199a6adb7e3e763bd558852b7947 and f4f345b12cd1fcb48d589fa9d2d189f5a604fe10

**Comment by hans-schmidt** [comment]
These binaries won't work on Ubuntu-18.04, will they?
Would it be better to use Ubuntu-18.04 instead of Ubuntu-20.04?

**Comment by fdoving** [comment]
The idea with this Dockerfile is to setup and run a node.
In this case I think it makes sense to use a newer base.

Ubuntu 18.04 is close to EOL, apart from it's core, which has support for two more years.
I think it makes sense to move on where we can.

**Comment by hans-schmidt** [comment]
OK. Approved.

**Pull request merged**
