### PR TITLE
Moving to DGW when RIP-2 is activated.

### PR DESCRIPTION
**Pull request by cfox**
Proposal to move to Dark Gravity Wave for pow difficulty readjustment.  Will activate at the same time as assets (RIP-2).

### CODE REVIEW

**Comment by lsji07** [comment]
Thanks guys!

**Comment by cryptforall** [comment]
Yup Agree with @underdarkskies i've tested the LWMA with x16r for a good mth, DGW doesn't even compare.

**Comment by russkidooski** [comment]
I agree LWMA might be a better choice, But it's pretty new and might have some vulnerabilities.

**Comment by cryptforall** [comment]
https://github.com/zawy12/difficulty-algorithms/issues/3 very actively watched and patched.

**Comment by Sledgemoto** [comment]
Zawn'y has been very helpful and active in the discord development channel. I'm sure if asked he would help with the implementation or at least consult.

**Comment by JohnELester** [comment]
There's also a thread in our subreddit talking about this: https://www.reddit.com/r/Ravencoin/comments/92v9ab/pull_request_now_on_github_to_fix_rvn_diff_swings/

**Comment by cfox** [comment]
We're pressed for time to get this July release out.  We're going to go with DGW for now because it's what we have and it represents progress.  Let's continue evaluation/discussion and if we have another release before fork maybe we can get LWMA in.  Thanks!

**Pull request merged**
