### PR TITLE
Update: protocol update to 70029 for p2sh (PR #965)

### PR DESCRIPTION
**Pull request by HyperPeek**
This updates the protocol version to 70029.

### CODE REVIEW

**Comment by HyperPeek** [comment]
The MIN_PEER_PROTO_VERSION is currently set to X16RV2_VERSION, which is 70025. Changing this would disconnect nodes prior to the defined version. So we want to keep this as is.

**Comment by jeroz1** [comment]
While you are editing this file, there are typos in lines 24 and 27 ("reutrn"). 

Whats the purpose of those constants integers in this version file? Is it for documentation or are they used? If it's the former, should 70028 be documented?

**Comment by HyperPeek** [comment]
Constants are used, mainly for forks. E.g. KAWPOW_VERSION is used to disconnect from servers not running at least 70027. Typos fixed and (c) date extended to 2021.

**Comment by hans-schmidt** [comment]
P2SH does not change the P2P network protocol at all, so I advise against changing the rev #.
I propose that this PR should be closed unmerged.

**Comment by fdoving** [comment]
> P2SH does not change the P2P network protocol at all, so I advise against changing the rev #.
> I propose that this PR should be closed unmerged.

I agree.

**Comment by HyperPeek** [comment]
Ok -- I keep it here as draft until we have a solution for the p2sh check triggering on previous tx stopping the sync.

**Comment by HyperPeek** [comment]
Not needed

**Pull request closed without merging**
