### PR TITLE
Dockerfile for building and running a full ravend node

### PR DESCRIPTION
**Pull request by joecryptotoo**
I've enabled automation on Docker hub to build this image here:
https://hub.docker.com/r/joecryptotoo/ravencoin

Start one up yourself with these commands:

```
docker volume create --name=ravend-data
docker run -d -v ravend-data:/var/lib/raven \
        -p 8767:8767 \
        --name=ravend-node \
        --restart unless-stopped \
        joecryptotoo/ravencoin:latest
```

Donations: [RV9zdNeUTQUToZUcRp9uNF8gwH5LzDFtan](https://ravencoin.network/address/RV9zdNeUTQUToZUcRp9uNF8gwH5LzDFtan)

### CODE REVIEW

**Review by TronBlack — APPROVED** [review]
For use as a node.
EXPOSE port 8766 (Used for RPC calls)
Use -p 8766:8766 and modification of raven.conf with allowip=... if needed to call from external source, but protect any funded wallets with additional security.

**Comment by jeroz1** [comment]
Thanks for this!

Changing the calls `apt-get clean`  to `apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*` saves another whopping 1MB for me :)

**Comment by jeroz1** [comment]
Tested and working from source Dockerfile on a mac.

**Comment by joecryptotoo** [comment]
I just added a small change that should speed things up and save from having to download the same packages twice.

**Review by HyperPeek — APPROVED** [review]

**Comment by wangtao19911111** [comment]
> 我已经在 Docker hub 上启用了自动化来在这里构建这个图像： [https ://hub.docker.com/r/joecryptotoo/ravencoin](https://hub.docker.com/r/joecryptotoo/ravencoin)
> 
> 使用以下命令自行启动：
> 
> ```
> docker volume create --name=ravend-data
> docker run -d -v ravend-data:/var/lib/raven \
>         -p 8767:8767 \
>         --name=ravend-node \
>         --restart unless-stopped \
>         joecryptotoo/ravencoin:latest
> ```
> 
> 捐赠：[RV9zdNeUTQUToZUcRp9uNF8gwH5LzDFtan](https://ravencoin.network/address/RV9zdNeUTQUToZUcRp9uNF8gwH5LzDFtan)

how to config rpcuser and rpcpassword?

**Pull request closed without merging**
