### PR TITLE
Develop merge into Master for the v4.6.1 mainnet release

### PR DESCRIPTION
**Pull request by hans-schmidt**
This is the merge of the develop branch into master, including all the improvements made and tested over the last 2 years with the exception of P2SH asset support, which is not included.

There are quite a few bug fixes and GUI improvements, but NO changes in consensus.

### CODE REVIEW

**Comment by jeroz1** [comment]
I cross checked all commits, and they seem ok to me. @TronBlack 

One thing to think about is updating the build pipeline:

```
Build Raven: .github#L1
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

**Review by jeroz1 — APPROVED** [review]

**Comment by hans-schmidt** [comment]
I prefer not to update the build environment at this time.
Quite a few people are still using Ubuntu-18.04. But during the change from 18.04 to 20.04 the C library
	upgraded in a non-reverse compatible way. So if you build on 20.04, it won't run on 18.04. Instead
	it gives error messages about "`GLIBC_2.29' not found" and "`GLIBC_2.28' not found" because 18.04
	only supports GLIBC_2.27

**Review by TronBlack — APPROVED** [review]
+1
Should not change the consensus rules from version 4.3.2.1
Improves UI, includes some Bitcoin improvements, increased language support, and other non-consensus improvements.

**Review by HyperPeek — APPROVED** [review]
With leaving p2sh out of this merge this does not touch consensus, so I do not see a risk here. I have merged / seen / approved most individual commits before and apart from the language (.ts) files I checked the diffs once more.
Approved and good to go from my side -- great work!

**Comment by hans-schmidt** [comment]
Three approvals (not including me). Good to go.

**Pull request merged**
