### PR TITLE
Qt 5.12.10, openssl 1.1.1k, updated dependencies.

### PR DESCRIPTION
**Pull request by fdoving**
Depends and build-system updates.

Highlights:
  - Qt 5.12.10
  - openssl 1.1.1k
  - Improvements to the build-system.

When doing this PR against master branch, it includes the previous #904 changes.
Commit 3b459aa and 237233b are the changes after #904 

This PR and commit 3b459aa are big and touches a lot of files.
It can be broken down into smaller ones, if needed.  (Takes some work).

REGRESSION: Building shared libraries (libravenconsensus-0.dll) on Windows is disabled.
TESTING: Building on Windows and OSX is not tested. All my tests are done on Ubuntu 20.04 and github.com.

UPDATE: Cross compiling for OSX is now fixed, tested and works on Ubuntu 20.04. End result package not tested on OSX.

If you have too much RVN, donations are welcome: RFmtFb9GdZHvbvBW5hYB3s9VezJxeSfnz3

<strike>NOTE:
I'm making the PR to master, because develop is old.
If someone could update develop to not lag behind master, it would be helpful.
I think changes like this one should first be merged to develop. </strike>

### CODE REVIEW

**Review by HyperPeek — DISMISSED** [review]
We should think about a way to manually do osx builds at certain release points.

**Comment by fdoving** [comment]
I agree. I have gitian+ravencoin on my todo-list.
https://gitian.org/

**Comment by fdoving** [comment]
This breaks cross-compiling OSX binaries, with the SDK.

**Review by alisscco — APPROVED** [review]

**Review by alisscco — APPROVED** [review]

**Review by alisscco — APPROVED** [review]

**Review by HyperPeek — APPROVED** [review]
Remove the ISSUE_TEMPLATE commit during squash-merge, as it is already in PR #916

**Pull request closed without merging**
