### PR TITLE
Fix for Boost utf8_codecvt_facet warnings on macOS

### PR DESCRIPTION
**Pull request by volbil**
Couple system specific check to prevent `utf8_codecvt_facet` warnings spamming during compilation on macOS.

Before:
Before
After:
After

### CODE REVIEW

**Comment by volbil** [comment]
Sorry, not sure in which branch this PR should be addressed, so for now just leave it to master.

**Comment by blondfrogs** [comment]
@volbil Can you point this PR to the develop branch? That is the branch that will be released next.

**Comment by volbil** [comment]
@blondfrogs done :)

**Comment by blondfrogs** [comment]
#733

**Pull request closed without merging**
