### PR TITLE
Merge: develop into master

### PR DESCRIPTION
**Pull request by fdoving**
This PR is for merging develop into master to have a working master branch once again. This includes all merged PR's since the SIG started, excluding p2sh (PR #873) and sweep (PR #909), as these need further testing.  Testing will be done on the develop branch.

### CODE REVIEW

**Review by HyperPeek — APPROVED** [review]
Approved. We need a working master.

**Comment by hans-schmidt** [comment]
Approved

**Comment by hans-schmidt** [comment]
I woiuld approve if I could. GRRR....!%*^%$

**Review by hans-schmidt — APPROVED** [review]
Approved

**Pull request merged**
