### PR TITLE
Etardz

### PR DESCRIPTION
**Pull request by etardz**
ummm just trying to merge between "still think im fucking up" mybad yo

### CODE REVIEW

**Comment by etardz** [comment]
just trying to merge lanes "dont know if im doing it right"

**Comment by blondfrogs** [comment]
Not sure what you are trying to do here. Can you explain? Desktop.ini shouldn't be added to the repo.

**Comment by jeroz1** [comment]
I think etardz is trying to merge his own branches within his own git but accidentally made a PR here. The github GUI is a bit tricky if you try to merge things and by default wants to make PRs to the repo you forked from.

**Comment by blondfrogs** [comment]
Cool. Closing this PR

**Pull request closed without merging**
