### PR TITLE
Contrib: Copy install_db4.sh from bitcoin (PR #934).

### PR DESCRIPTION
**Pull request by fdoving**
This script automates the process of downloading and compiling Berkeley DB 4.8.
    Rebranded to Ravencoin

### CODE REVIEW

**Review by HyperPeek — COMMENTED** [review]
Just to make sure that the inline patch between ln 71 and 219 with the various diffs is wanted and works :-)

**Review by HyperPeek — APPROVED** [review]
Did a quick test locally and it looks ok.

**Comment by hans-schmidt** [comment]
This is literally a direct copy of the file from the bitcoin repo.
But if you are going to change "bitcoin" to "Ravencoin" in line 247, then you might as well also do it in line 15.

**Comment by fdoving** [comment]
> This is literally a direct copy of the file from the bitcoin repo.
> But if you are going to change "bitcoin" to "Ravencoin" in line 247, then you might as well also do it in line 15.

Good catch. 
Fixed, not squashed.

**Pull request merged**
